version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  data-sender:
    build:
      context: ./data_sender
      dockerfile: Dockerfile.sender
    volumes:
      - ./ip_addresses.csv:/app/ip_addresses.csv
    depends_on:
      - backend